# Class: CSC-615-01 Spring 2020
# Name: Osbaldo Martinez
# Student ID: 916754207
# Project: <Assignment 1 - Traffic Light>
all: assigment1wpi assigment1b

assigment1wpi: assigment1wpi.c
	sudo gcc -Wall -o assigment1wpi assigment1wpi.c -lwiringPi

assigment1b: assigment1b.c
	sudo gcc -Wall -o assigment1b assigment1b.c
